---
extends: default

rules:
  line-length:
    max: 120
    level: warning
  document-start: disable
  truthy:
    check-keys: false
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1
  comments:
    min-spaces-from-content: 1
